from build123d import IN, MM

FIT = 0.2 * MM
LIP = 1.6 * MM
U = (1 + 3 / 4) * IN
SCREW_DIAMETER = 3 * MM
SCREW_HOLE_DIAMETER = SCREW_DIAMETER + FIT
SCREW_INSERT_DIAMETER = 4.5 * MM
SCREW_SUPPORT_DIAMETER = 1 / 4 * IN
TRAY_WIDTH = 8.25 * IN
TRAY_HEIGHT = 1 * U - (1 / 2 * IN)
TRAY_FACE_SCREW_HORIZONTAL_SPACING = TRAY_WIDTH - (1 / 2) * IN
TRAY_FACE_SCREW_VERTICAL_SPACING = TRAY_HEIGHT - (1 / 4) * IN
TRAY_FACE_HEIGHT = 1 * U - (1 / 8 * IN)
TRAY_EAR_WIDTH = 1 / 2 * IN
THICKNESS = 1 / 8 * IN
FACE_THICKNESS = 1 / 4 * IN
WALL_THICKNESS = 2.4 * MM
TRAY_LOCATIONS = ((-(17 + 1 / 4) / 4 * IN, 0), ((17 + 1 / 4) / 4 * IN, 0))
